controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

template:
    resource: ../../templates/producto/detalle.html.twig
    type: annotation